# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AreaRatioDialog
                                 A QGIS plugin
 Dialog to select layers for area ratio
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-11-25
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Zoltan Siki
        email                : siki.zoltan@epito.bme.hu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from PyQt5 import uic
from PyQt5 import QtWidgets
from qgis.PyQt.QtCore import Qt
from qgis.core import QgsMapLayerProxyModel

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'arearatio_dialog_base.ui'))


class AreaRatioDialog(QtWidgets.QDialog, FORM_CLASS):
    """ dialog to select parcel and building layers """

    def __init__(self, main, parent=None):
        """Constructor."""
        super(AreaRatioDialog, self).__init__(parent)
        self.main = main
        self.setupUi(self)

    def showEvent(self, event):
        """ initialize widgets """
        self.parcelLayerComboBox.setFilters(QgsMapLayerProxyModel.PolygonLayer)
        index = self.parcelLayerComboBox.findText(self.main.tool.poly_layer_name)
        if index >= 0:
            self.parcelLayerComboBox.setCurrentIndex(index)
        for i in range(0, self.parcelLayerComboBox.count()):
            name = self.parcelLayerComboBox.itemText(i)
            self.buildingsComboBox.addItem(name)
        # select building layers
        for in_layer in self.main.tool.in_poly_layers:
            index = self.buildingsComboBox.findText(in_layer)
            if index >= 0:
                self.buildingsComboBox.setItemCheckState(index, Qt.CheckState.Checked)

